name: Image Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: classic-build

jobs:
  proxy:
    name: "Transfer Pod Image"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '!norun') }}
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.TOKEN }}
      - uses: docker/build-push-action@v3.3.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/minestudio-host/util:transfer